version: '3'

networks:
  app-tier:
    driver: bridge

services:
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - REDIS_REPLICATION_MODE=master
      - ALLOW_EMPTY_PASSWORD=yes
      #- REDIS_PASSWORD=str0ng_passw0rd
    networks:
      - app-tier
    ports:
      - '6379'
  
  redis-slave:
    image: 'bitnami/redis:latest'
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis
      - ALLOW_EMPTY_PASSWORD=yes
      #- REDIS_MASTER_PASSWORD=str0ng_passw0rd
      #- REDIS_PASSWORD=str0ng_passw0rd
    ports:
      - '6379'
    depends_on:
      - redis
    networks:
      - app-tier
  
  redis-sentinel:
    image: 'bitnami/redis-sentinel:latest'
    environment:
      #- REDIS_MASTER_PASSWORD=str0ng_passw0rd
      - ALLOW_EMPTY_PASSWORD=yes
    depends_on:
      - redis
      - redis-slave
    ports:
      - '26379-26381:26379'
    networks:
      - app-tier

  redis-demo-app:
    build: ../redis-demo-app
    networks:
      - app-tier
    ports:
      - '8080:8080'
    links:
      - redis
      - redis-slave
      - redis-sentinel